from langchain_core.messages import AIMessage


# temp AI message generated by the agent for pdf generation
temp_summary = AIMessage(
    content='''FORM – IF1 - (Integrated Form) \n \nFIRST INFORMATION REPORT
\n(Under Section 154 Cr.P.C) \n \n1. Dist. ……………..   P.S. ………………. Year 
……………..  F.I.R. No. …………….  Date …………   \n \n2. (i) *Act BNS *Sections 
303(2)\n (ii) *Act …………………………………. *Sections  ……………………………………………...  \n 
(iii)  *Act …………………………………. *Sections  ……………………………………………... \n (iv)  * 
Other Acts & Sections  ……………………………………………………………………….. \n\n3.  \n(a) \n \n*
Occurrence of Offence: * Day ……………….*Date 30 June 2026 *Time around 4:00 
PM  \n  \n(b) \n \nInformation received at P.S.  Date ………………………… Time 
…………………………….. \n  \n(c)  \n \nGeneral Diary Reference: Entry No(s) 
…………………… Time ………………………………  \n \n4. Type of information :     *Written / 
Oral  \n \n5. Place of occurrence:  (a) Direction and Distance from P.S. 
………………… Beat No. …………….. \n \n (b) * Address near Akash Deep Enclave, 
City Centre Mall, Kolkata, West 
Bengal\n……………………………………………………………………………………………………………. \n (c) In case outside
limit of this Police Station, then the name of P.S. …………………………….. 
\nDistrict Kolkata ……………………………  \n \n6. Complainant / information :  \n 
\n (a) Name Harshit Singh \n \n (b) Father’s / Husband’s Name rk singh\n 
\n (c)\nDate / Year of Birth  ……………………………………… (d) Nationality Indian    
\n (e) Passport No: ………………….. Date of Issue: ……………….. Place of Issue 
……………….. \n (f) Occupation: Software Engineer  \n \n \n(g) Address: 14 
Akash Deep Enclave, Kolkata, West Bengal \n7. Details of known / 
suspected / unknown / accused with full particulars \n(Attach separate 
sheet if necessary):  \na man wearing a black hoodie and blue 
jeans\n………………………………………………………………………………………………………….. \n……………………………… 
………………………………………………………………………….. 
\n………………………………………………………………………………………………………….. \n8. Reasons for delay in 
reporting by the  complainant / Informant searching for the motorcycle in
nearby areas and also checking with local security 
guards\n…………………………………………………………………………………………………………  
\n…………………………………………………………………………………………………………. \n9. Particulars of 
properties stolen / involved (Attach separate sheet if ne cessary): black
Royal Enfield Classic 350 motorcycle, estimated value ₹1,80,000''',
    additional_kwargs={},
    response_metadata={
        'model': 'gemma4:26b',
        'created_at': '2026-07-01T11:47:42.2521547Z',
        'done': True,
        'done_reason': 'stop',
        'total_duration': 128386406300,
        'load_duration': 410960000,
        'prompt_eval_count': 1221,
        'prompt_eval_duration': 5064741000,
        'eval_count': 2228,
        'eval_duration': 122774002000,
        'logprobs': None,
        'model_name': 'gemma4:26b',
        'model_provider': 'ollama'
    },
    id='lc_run--019f1d7f-aaa9-7d03-87ce-35660a33c067-0',
    tool_calls=[],
    invalid_tool_calls=[],
    usage_metadata={
        'input_tokens': 1221,
        'output_tokens': 2228,
        'total_tokens': 3449
    }
)